# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-02-26 01:08:09
"""
import arcpy

def Model1():  # Model 1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"F:\software\LAStools\ArcGIS_toolbox\LAStools.tbx")
    jtsk_pas1_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas1.las"
    full = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\full"
    jtsk_pas2_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas2.las"
    jtsk_pas3_las_2_ = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas3.las"
    jtsk_pas4_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas4.las"
    jtsk_pas5_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas5.las"
    jtsk_pas6_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas6.las"
    jtsk_pas7_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas7.las"
    jtsk_pas8_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas8.las"
    jtsk_pas10_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas10.las"
    jtsk_pas9_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas9.las"

    # Process: lasgrid (lasgrid) 
    lasgrid(input_file=jtsk_pas1_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (2) (lasgrid) 
    lasgrid(input_file=jtsk_pas2_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_2_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (3) (lasgrid) 
    lasgrid(input_file=jtsk_pas3_las_2_, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_3_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (4) (lasgrid) 
    lasgrid(input_file=jtsk_pas4_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_4_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (5) (lasgrid) 
    lasgrid(input_file=jtsk_pas5_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_5_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (6) (lasgrid) 
    lasgrid(input_file=jtsk_pas6_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_6_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (7) (lasgrid) 
    lasgrid(input_file=jtsk_pas7_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_7_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (8) (lasgrid) 
    lasgrid(input_file=jtsk_pas8_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_8_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (10) (lasgrid) 
    lasgrid(input_file=jtsk_pas10_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_10_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (9) (lasgrid) 
    lasgrid(input_file=jtsk_pas9_las, step=1, item="elevation", operation="lowest", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="", output_file=output_file_9_, output_directory=full, output_appendix="", additional_command-line_parameters="", verbose=True)

    # Process: lasmerge (lasmerge) 
    jtsk_pas1_9 = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas1-9.las"
    lasmerge(input_file_1=jtsk_pas1_las, input_file_2=jtsk_pas2_las, input_file_3=jtsk_pas3_las_2_, input_file_4=jtsk_pas4_las, input_file_5=jtsk_pas5_las, input_file_6=jtsk_pas6_las, input_file_7=jtsk_pas7_las, input_file_8=jtsk_pas8_las, input_file_9=output_file_9_, output_file=jtsk_pas1_9, additional_command-line_parameters="", verbose=True)

    # Process: lasmerge (2) (lasmerge) 
    jtsk_pas1_10_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\full\\jtsk_pas1-10.las"
    lasmerge(input_file_1=jtsk_pas1_9, input_file_2=jtsk_pas10_las, input_file_3="", input_file_4="", input_file_5="", input_file_6="", input_file_7="", input_file_8="", input_file_9="", output_file=jtsk_pas1_10_las, additional_command-line_parameters="", verbose=True)

    # Process: lasgrid (11) (lasgrid) 
    lasgrid(input_file=jtsk_pas1_10_las, step=1, item="elevation", operation="stddev", fill_voids_searching_n_neighbor_pixels=0, output="actual values", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, grid="all points", use_bounding_box=False, use_tile_bounding_box=False, output_format="tif", output_file=output_file_11_, output_directory=full, output_appendix="_dem", additional_command-line_parameters="", verbose=True)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\michal\Desktop\_BP\gis\Lucni_point_cloud\Lucni_point_cloud.gdb", workspace=r"C:\Users\michal\Desktop\_BP\gis\Lucni_point_cloud\Lucni_point_cloud.gdb"):
        Model1()
