# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-03-04 23:49:07
"""
import arcpy

def Model1():  # Model 1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")

    arcpy.ImportToolbox(r"F:\software\LAStools\ArcGIS_toolbox\LAStools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(cellSize="0,05", snapRaster=r"KRNAP\2019_06_14_Lucni_2_DSM.tif"):
        jtsk_pas3_area81_las_2_ = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas3_area81.las"
        grid_size = 0,05
        keep = "lowest"
        jtsk_pas4_area81_las_2_ = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas4_area81.las"
        jtsk_pas5_area81_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas5_area81.las"
        jtsk_pas6_area81_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas6_area81.las"
        jtsk_pas7_area81_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas7_area81.las"
        jtsk_pas8_area81_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas8_area81.las"

        # Process: lasthin (lasthin) 
        lasthin(input_file=jtsk_pas3_area81_las_2_, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas3_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (las2dem) 
        las2dem(input_file=jtsk_pas3_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas3_area81_dem_tif, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (HillShade) 
        jtsk_pas3_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas3_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas3_area81_dem_tif, out_raster=jtsk_pas3_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasthin (2) (lasthin) 
        lasthin(input_file=jtsk_pas4_area81_las_2_, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas4_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (2) (las2dem) 
        las2dem(input_file=jtsk_pas4_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas4_area81_dem_tif, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (2) (HillShade) 
        jtsk_pas4_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas4_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas4_area81_dem_tif, out_raster=jtsk_pas4_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasthin (3) (lasthin) 
        lasthin(input_file=jtsk_pas5_area81_las, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas5_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (3) (las2dem) 
        las2dem(input_file=jtsk_pas5_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas5_area81_dem_tif, output_directory="", output_appendix="_dem", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (3) (HillShade) 
        jtsk_pas5_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas5_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas5_area81_dem_tif, out_raster=jtsk_pas5_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasthin (4) (lasthin) 
        lasthin(input_file=jtsk_pas6_area81_las, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas6_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (4) (las2dem) 
        las2dem(input_file=jtsk_pas6_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas6_area81_dem_tif, output_directory="", output_appendix="_dem", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (4) (HillShade) 
        jtsk_pas6_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas6_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas6_area81_dem_tif, out_raster=jtsk_pas6_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasthin (5) (lasthin) 
        lasthin(input_file=jtsk_pas7_area81_las, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas7_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (5) (las2dem) 
        las2dem(input_file=jtsk_pas7_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas7_area81_dem_tif, output_directory="", output_appendix="_dem", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (5) (HillShade) 
        jtsk_pas7_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas7_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas7_area81_dem_tif, out_raster=jtsk_pas7_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasthin (6) (lasthin) 
        lasthin(input_file=jtsk_pas8_area81_las, grid_size=grid_size, keep=keep, output_format="", output_file=jtsk_pas8_area81_thin_min_las, output_directory="", output_appendix="", additional_command-line_parameters="", verbose=True)

        # Process: las2dem (6) (las2dem) 
        las2dem(input_file=jtsk_pas8_area81_thin_min_las, step=0,05, kill_triangles_with_edges_longer_than=100, item="elevation", output="actual values", sun_direction_for_hillside_shading="north east", sun_position_for_hillside_shading="1 pm", set_min__for_gray_ramp_and_false_colors_=None, set_max__for_gray_ramp_and_false_colors_=None, triangulate="all points", use_tile_bounding_box=False, closed_breaklines="", open_breaklines="", output_format="tif", output_file=jtsk_pas8_area81_dem_tif, output_directory="", output_appendix="_dem", additional_command-line_parameters="", verbose=True)

        # Process: HillShade (6) (HillShade) 
        jtsk_pas8_area81_hillshade_tif = "C:\\Users\\michal\\Desktop\\_BP\\gis\\las_pasy_dem\\lastools\\area_n81\\hillshade\\jtsk_pas8_area81_hillshade.tif"
        arcpy.HillShade_3d(in_raster=jtsk_pas8_area81_dem_tif, out_raster=jtsk_pas8_area81_hillshade_tif, azimuth=315, altitude=45, model_shadows="NO_SHADOWS", z_factor=1)

        # Process: lasmerge (lasmerge) 
        jtsk_pas3_8_area81_las = "C:\\Users\\michal\\Desktop\\_BP\\Krkonose\\LiDAR\\area_81\\jtsk_pas3-8_area81.las"
        lasmerge(input_file_1=jtsk_pas3_area81_las_2_, input_file_2=jtsk_pas4_area81_las_2_, input_file_3=jtsk_pas5_area81_las, input_file_4=jtsk_pas6_area81_las, input_file_5=jtsk_pas7_area81_las, input_file_6=jtsk_pas8_area81_las, input_file_7="", input_file_8="", input_file_9="", output_file=jtsk_pas3_8_area81_las, additional_command-line_parameters="", verbose=True)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\michal\Desktop\_BP\gis\Lucni_point_cloud\Lucni_point_cloud.gdb", workspace=r"C:\Users\michal\Desktop\_BP\gis\Lucni_point_cloud\Lucni_point_cloud.gdb"):
        Model1()
